# テーブルのうち静的なテーブルのみを更新する

use l1jdb;
charset utf8;

#source MyISAM/accounts.sql;
source MyISAM/area.sql;
source MyISAM/armor.sql;
#source MyISAM/ban_ip.sql;
source MyISAM/beginner_items.sql;
#source MyISAM/board.sql;
#source MyISAM/board_auction.sql;
#source MyISAM/castle.sql;
#source MyISAM/character_buddys.sql;
#source MyISAM/character_buffs.sql;
#source MyISAM/character_config.sql;
#source MyISAM/character_quests.sql;
#source MyISAM/character_skills.sql;
#source MyISAM/character_teleport.sql;
#source MyISAM/characters.sql;
#source MyISAM/clan_data.sql;
source MyISAM/commands.sql
source MyISAM/cooking_ingredients.sql;
source MyISAM/cooking_recipes.sql;
source MyISAM/door_gfxs.sql
#source MyISAM/connection_test_table.sql;
source MyISAM/drop_item.sql;
source MyISAM/droplist.sql;
source MyISAM/dungeon.sql;
source MyISAM/dungeon_random.sql
source MyISAM/etcitem.sql;
source MyISAM/getback.sql;
source MyISAM/getback_restart.sql;
#source MyISAM/house.sql;
#source MyISAM/inn_key.sql;
#source MyISAM/inventory_items.sql;
#source MyISAM/inn.sql;
#source MyISAM/letter.sql;
#source MyISAM/log_chat.sql;
#source MyISAM/log_enchant.sql;
source MyISAM/magic_doll.sql
source MyISAM/mapids.sql;
source MyISAM/mobgroup.sql;
source MyISAM/mobskill.sql;
source MyISAM/npc.sql;
source MyISAM/npcaction.sql;
#source MyISAM/pets.sql;
source MyISAM/pettypes.sql;
source MyISAM/polymorphs.sql;
source MyISAM/shop.sql;
source MyISAM/skills.sql;
source MyISAM/spawnlist.sql;
source MyISAM/spawnlist_boss.sql;
source MyISAM/spawnlist_door.sql;
source MyISAM/spawnlist_npc.sql;
source MyISAM/spawnlist_time.sql;
source MyISAM/spawnlist_trap.sql;
source MyISAM/spawnlist_ub.sql;
source MyISAM/spr_action.sql;
source MyISAM/spr_list.sql;
#source MyISAM/town.sql;
source MyISAM/trap.sql;
source MyISAM/ub_managers.sql;
source MyISAM/ub_settings.sql;
source MyISAM/ub_times.sql;
source MyISAM/weapon.sql;
source MyISAM/weapon_skill.sql
